Add playground
10up/figma-block pull request #29
Opened 2024-08-16 14:17 UTC by thrijith

### Description of the Change

- This adds blueprint to for enabling live preview on wp.org playground

Closes https://github.com/10up/figma-block/issues/27

### How to test the Change

- Go to https://github.com/10up/figma-block/tree/feature/add-playground?tab=readme-ov-file, confirm you can see the playground label, this is not functional right now, until the plugin is published on wp.org

### Changelog Entry

> Added - Enable playground for Plugin.

### Credits
Props @jeffpaul, @thrijith 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [x] All new and existing tests pass.

2024-08-16 16:43 UTC, dkotter requested changes
So this works (well it will work once the plugin is on .org) but it just lands you on a blank edit screen. I'd suggest for a better experience, we actually create a page that has the Figma Block, with an actual Figma URL already set in the block. This will be a better preview experience than forcing someone to add the block themselves

2024-08-20 21:22 UTC, dkotter requested changes

2024-08-20 21:22 UTC, dkotter commented on .wordpress-org/blueprints/blueprint.json
> +      "step": "importFile",
`importFile` has been deprecated and this should be `importWxr` instead

2024-08-20 21:22 UTC, dkotter commented on .wordpress-org/blueprints/blueprint.json
> +        "url": "https:\/\/raw.githubusercontent.com\/10up\/figma-block\/05a11e7ed51038173610e543cb02fc56024f0c1f\/.wordpress-org\/blueprints\/demo-data.xml"
We'll probably want to ensure this URL get's updated to point to `develop` before this is merged

2024-08-21 16:33 UTC, dkotter approved these changes

2024-08-28 17:09 UTC, jeffpaul approved these changes

2024-08-28 17:09 UTC, merged