Add E2E Tests
10up/figma-block pull request #37
Opened 2024-09-17 20:53 UTC by sksaju

### Description of the Change

Add E2E tests to the plugin.

Closes https://github.com/10up/embed-block-figma/issues/19

### How to test the Change

Run E2E tests by running:

- npm install
- npm run cypress:run

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability
> Developer - Non-functional update

- Added - E2E tests

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

2024-09-20 19:58 UTC, dkotter requested changes

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}
Our minimum WP version for this plugin is 6.4
```suggestion
          - {name: 'WP minimum', version: 'WordPress/WordPress#6.4'}
```

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +      uses: actions/checkout@v3
```suggestion
      uses: actions/checkout@v4
```

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +      uses: actions/cache@v3
```suggestion
      uses: actions/cache@v4
```

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +    - name: Cache node_modules
Probably want a step before this where we install the proper node version, see https://github.com/10up/insecure-content-warning/blob/develop/.github/workflows/cypress.yml#L39

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +      run: npm install
```suggestion
      run: npm ci
```

2024-09-20 19:58 UTC, dkotter commented on .github/workflows/cypress.yml
> +      run: composer install
Not tested removing but don't think we actually need this step

2024-09-20 19:58 UTC, dkotter commented on .gitignore
> +tests/cypress/downloads
Can probably just ignore the entire `tests` directory

2024-09-20 19:58 UTC, dkotter commented on package.json
> +    "cypress-mochawesome-reporter": "^3.4.0"
I think this should be a dev-dependency

2024-09-20 19:58 UTC, dkotter commented on tests/bin/set-wp-config.js
> +#!/usr/bin/env node
I've not compared line by line but I know this is slightly different than the most recent version of this we've done. Can see that here: https://github.com/10up/insecure-content-warning/blob/develop/tests/bin/set-wp-config.js

2024-09-20 19:58 UTC, dkotter commented on tests/cypress/e2e/admin.cy.js
> +	});
We can probably remove this test

2025-01-14 03:22 UTC, jeffpaul commented
@dkotter any additional updates desired here before getting this merged in?

2025-01-14 15:23 UTC, dkotter requested changes

2025-01-14 15:23 UTC, dkotter commented on package.json
> +    "sharp": "^0.33.5"
Curious why we're adding a new dependency here? Doesn't seem like this is needed for this particular PR

2025-01-14 15:24 UTC, dkotter commented
> @dkotter any additional updates desired here before getting this merged in?

Left one more comment that I think needs updating. Otherwise seems tests aren't passing so will need to get those fixed up but then this will be good to merge

2025-03-13 18:47 UTC, jeffpaul commented on .gitignore
> +tests/cypress/downloads
updated in [9a33b0e](https://github.com/10up/embed-block-figma/pull/37/commits/9a33b0e856119bf1f774360dbe10d1c7961cceb7)

2025-03-13 19:33 UTC, jeffpaul commented on package.json
> +    "sharp": "^0.33.5"
done in [afdfc9d](https://github.com/10up/embed-block-figma/pull/37/commits/afdfc9dd846ee3c168b261c54acd0de64c4c59b2)

2025-03-13 19:39 UTC, jeffpaul commented on tests/bin/set-wp-config.js
> +#!/usr/bin/env node
Addressed in [4cb85c9](https://github.com/10up/embed-block-figma/pull/37/commits/4cb85c9b3d609202529cb39f4daaa003d30619d7)

2025-03-13 21:02 UTC, jeffpaul commented
I've noodled on this for a while today (with the help of Cursor) but cannot seem to get Cypress to properly trigger the block inserter or utilize a slash command to open the Figma block.  I'm going to put this down for now and come back later to see if a fresh approach shakes something loose.

2025-03-14 17:41 UTC, dkotter commented
E2E tests should be passing now in our minimum environment (6.5) and the current release (6.7). They are failing in 6.8-beta due to markup changes around the block inserter. This will be fixed in our utils package (see https://github.com/10up/cypress-wp-utils/pull/131) once a new release goes out there

2025-03-27 18:04 UTC, iamdharmesh approved these changes
LGTM 🚀 . Thank you for your efforts here @sksaju @jeffpaul @dkotter.

2025-03-27 18:07 UTC, iamdharmesh commented
@dkotter I am unable to merge this because merging is blocked due to the requested changes from your end. Please merge it whenever you can. Thanks!

2025-03-30 16:01 UTC, merged